### ISSUE TITLE
Cve search

### ISSUE THREAD

**Issue by spoorcc** [dfetch-org/dfetch#113]
For all dependencies create a cpe and use https://github.com/cve-search/PyCVESearch to search for known security issues

**Comment by spoorcc** [comment]
Food for thought: https://www.veracode.com/blog/managing-appsec/using-cpes-open-source-vulnerabilities-think-again

**Comment by spoorcc** [comment]
https://github.com/AppThreat/dep-scan might be interesting

**Comment by spoorcc** [comment]
Or https://github.com/barnumbirr/ares which uses circl

**Comment by ben-edna** [comment]
DFetch should never go looking for vulnerabilities. Just generate a SBoM as suggested in #154 and let the user use that to track issues.
