### ISSUE TITLE
Cannot use dst tag for single source file (git)

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#120]
Below scenario doesn't work: 
```gherkin
        Given the manifest 'dfetch.yaml' in MyProject
            """
            manifest:
                version: 0.0
                projects:
                    - name: SomeProjectWithAnInterestingFile
                      url: some-remote-server/SomeProjectWithAnInterestingFile.git
                      dst: SomeFile.txt
                      src: SomeFolder/SomeFile.txt
                      tag: v1
            """
        And a git-repository "SomeProjectWithAnInterestingFile.git" with the files
            | path                                  |
            | SomeFolder/SomeFile.txt               |
            | SomeOtherFolder/SomeOtherFile.txt     |
        When I run "dfetch update"
        Then the output shows
            """
            Dfetch (0.0.6)
              SomeProjectWithAnInterestingFile: Fetched v1
            """
        Then 'MyProject' looks like:
            """
            MyProject/
                .dfetch_data-SomeFile.txt.yaml
                SomeFile.txt
                dfetch.yaml
            """
```

**Comment by ben-edna** [comment]
From @jgeudens :
> I looked a little further at the checkout of 1 single file from git (# 120). I have already solved some things, but I see a possible improvement. The destination of project in the manifest is stored in the `Project` object. In the git module this is requested via `self.localproject`. This is used as the base directory (also in svn.py). But the problem is if this localproject var is a file then the `dirname` is an empty string. This `dirname` is then used to run commands that fail because they don't expect an empty string, but rather a "." from current dir. So the question is really: shall I fix this locally in the git.py module, since apparently it now works in svn.py? Or do you want to solve this at a higher level like always creating local project "./somefile.txt" or "./someFolder/"? 

- So the problem is in `_fetch_impl` I guess, and with the `self.local_path` member?
- The SvnRepo is correct indeed (see `Feature: Fetch single file from svn repo`).
- I think we first should try to solve it for git that we know what the root issue is, and we can optionally generalize the solution in a second step.

**Comment by jgeudens** [comment]
Ok, thank you for the thoughts. I will give it a try.

**Comment by jgeudens** [comment]
I'm a bit confused by the dst tag in this scenario. When using the dst option in other use cases, dst will serve as the folder in which to place the files/folders. But what does dst mean in this scenario? The name of the resulting file? If so, can this be another name then the source file?

Wouldn't it make more sense that the dst tag is always a folder? When omitted, it uses the default behavior and when provided, it will fetch `SomeFile.txt` into the dst folder.

**Comment by jgeudens** [comment]
Ok, but what happens when the source is a folder and the destination a file?

**Comment by ben-edna** [comment]
Hmmm, good point 😊 , what about ignoring the `dst:` in that case and warning the user that happened?

```gherkin
    Scenario: Using file as destination with a folder source
        Given the manifest 'dfetch.yaml' in MyProject
            """
            manifest:
                version: 0.0
                projects:
                    - name: SomeProjectWithAnInterestingFile
                      url: some-remote-server/SomeProjectWithAnInterestingFile.git
                      dst: SomeFile.txt
                      src: SomeFolder
                      tag: v1
            """
        And a git-repository "SomeProjectWithAnInterestingFile.git" with the files
            | path                                  |
            | SomeFolder/SomeFile.txt               |
        When I run "dfetch update"
        Then the output shows
            """
            Dfetch (0.0.6)
            SomeProjectWithAnInterestingFile: destination SomeFile.txt is a file but source is a folder, ignoring dst from the manifest.
              SomeProjectWithAnInterestingFile: Fetched v1
            """
        Then 'MyProject' looks like:
            """
            MyProject/
                SomeProjectWithAnInterestingFile/
                    .dfetch_data.yaml
                    SomeFile.txt
                dfetch.yaml
            """
```

**Comment by spoorcc** [comment]
Another good point :smile:, then let the user experience his own mistake? 
Easiest most predictable behavior is If source is either file or directory just use the name provided in dst. 

If the user has a dir as source, and provides a filename-like dst. Create a directory named after that file. If he has a file as source and a dirname as dst, then use the dirname as filename.

So, no clever stuff, do what the user told us, and let him notice if stuff goes wrong.

**Comment by jgeudens** [comment]
At the moment, the destination is created first and the sparse checkout is done in this folder. So this means that it isn't known that source is a file or directory when dst is created.

Should we checkout in a temporary directory and then create dst and copy files?

What do you think?
