### ISSUE TITLE
SVN support for dfetch import

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#17]
Currently import only supports Git.
Add support for SVN.

**Comment by jgeudens** [comment]
It appears that SVN is now required to be installed on the system to be able to run the import command.

**Comment by spoorcc** [comment]
Ah, off course :see_no_evil:

**Comment by spoorcc** [comment]
Created #73

**Comment by ben-edna** [comment]
mmm, could you paste `dfetch -v import` output? "It works on my machine"
