### ISSUE TITLE
Add list command

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#20]
Add a command that can list the current state of the projects.

For each project aggregate the metadata and list it.

**Comment by KrisEDNA** [comment]
@ben-edna, am I correct to assume this command should list the information that is provided in the manifest file?

**Comment by spoorcc** [comment]
I was also thinking about the metadata file (.dfetch_data.yaml). Last fetch for instance. 

So a combination of information between manifest and the metadata file. 

I think we can extend this in the future and this is just a first iteration

**Comment by KrisEDNA** [comment]
Okay, I'll give it a try.
