### ISSUE TITLE
Support for patch files

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#22]
After a project is fetched, apply a patch to apply any local changes.

Add a new attribute `patch:` to the manifest which gives an absolute path or a path relative to the manifest with a patch file (unified-diff git/svn). This will be applied after fetching a project, but before hashing it.

Don't assume any tooling on the system and use a pure python library (https://libraries.io/pypi/patch)

Don't forget:
- The documentation in `manifest.py` explaining this new attribute.
- Feature/Unit tests 
- Add `patch:` to the schema for validation to succeed.
- Add any external lib license to `legal.rst` (and make sure it is MIT compatible)

**Comment by jgeudens** [comment]
The path library seems a bit out of date. There is a fork because PR weren't being merged: https://github.com/conan-io/python-patch-ng

An good alternative seems to be https://pypi.org/project/diff-match-patch/

**Comment by ben-edna** [comment]
Patch-ng looks to me like good alternative since it is based on the patch library and we could switch back if that becomes active again.
