### ISSUE TITLE
Diff command with changes in working copy

### ISSUE THREAD

**Issue by jgeudens** [dfetch-org/dfetch#254]
It would be nice that the diff command can also generate a patch based on the changes in working copy.

My use case is the following:

1. Use dfetch to add component
2. Commit as-is in project
3. Do local changes in component and verify changes
4. dfetch diff to get patch
5. add patch to manifest
6. Commit all local changes in one commit

Sample feature test:
```

    Scenario: A patch file is generated
        Given "SomeProject/README.md" in MyProject is changed
            """
            An important sentence for the README!
            """
        When I run "dfetch diff SomeProject"
        Then the patch file 'MyProject/SomeProject.patch' is generated
            """
            diff --git a/README.md b/README.md
            xxx
            """
```

**Comment by ben-edna** [comment]
Good point!
