### ISSUE TITLE
Show spinner during long running operations

### ISSUE THREAD

**Issue by spoorcc** [dfetch-org/dfetch#264]
Currently dfetch 'feels' unresponsive when a fetch is done. Maybe use something like:  https://pythonawesome.com/beautiful-spinners-for-terminal-ipython-and-jupyter/

**Comment by ben-edna** [comment]
![spinner](https://user-images.githubusercontent.com/37540691/146694229-81bfc68e-0214-4df9-9f9a-24311079f4b2.gif)

**Comment by ben-edna** [comment]
@jgeudens : Currently only during fetch, also do it during check / determining versions

**Comment by jgeudens** [comment]
:tada:
