### ISSUE TITLE
Improve handling of corrupt .dfetch_data.yaml

### ISSUE THREAD

**Issue by jgeudens** [dfetch-org/dfetch#280]
I was rebasing a branch on master when both have changes in the dfetch.yaml and thus in the .dfetch_data.yaml. Because of a merge conflict, the data file was not valid.

The dfetch commands fail without information of the root cause. I was greeted with a Python traceback with too much information.

* `dfetch check` failed with a traceback
* `dfetch validate` was successful
* `dftech update --force` also failed with a traceback

Possible improvements:
* Catch exception and show error message about corrupt data file
* `dfetch update --force` should always work even when data file is corrupt to fix the issue

**Comment by spoorcc** [comment]
Good point, created a reproducing scenario
