### ISSUE TITLE
Importlib ModuleNotFoundError python 3.7.0

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#32]
`dfetch` uses importlib to find the reosurces in the package (template.yaml, schema). 
Users with pythn 3.7.0 report:

```bash
ModuleNotFoundError: No module named 'importlib.resources'
```

When running dfetch nder python 3.7.0

[`importlib.resources`](https://docs.python.org/3.9/library/importlib.html#module-importlib.resources) should be part of 3.7.0, to be investigated.

**Comment by ben-edna** [comment]
Workaround is to install a newer version, python 3.7.9 is reported to work

**Comment by KrisEDNA** [comment]
Work-around (tested on python 3.6.5):
```bash
pip install importlib-resources
```
```diff
--- a/dfetch/resources/__init__.py
+++ b/dfetch/resources/__init__.py
@@ -1,6 +1,9 @@
 """Resources needed when dfetch is distributed."""

-import importlib.resources as pkg_resources
+try:
+    import importlib.resources as pkg_resources
+except ModuleNotFoundError:
+    import importlib_resources as pkg_resources

 from dfetch import resources  # pylint: disable=import-self
```
