### ISSUE TITLE
dfetch check interpret tags

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#46]
Make it possible to interpret semver tags.

[Semantically versioned](https://semver.org/) tags could be interpreted. If for instance tag v3.4 is pinned but a tag v3.5 is available, notify the user that a 'newer' version is available.

**Comment by spoorcc** [comment]
https://python-semver.readthedocs.io/en/latest/usage.html#dealing-with-invalid-versions seems usefull

**Comment by spoorcc** [comment]
Can list tags for both svn & git: fb9adff9d7f892ab2d315b8ee9d6168798aef2f0
