### ISSUE TITLE
asciinema player upgrade

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#577]
asciinema-player 0.4.0 breaks the asciinema in the docs

Something about MIME-type (to be investigate)
![image](https://github.com/dfetch-org/dfetch/assets/37540691/b02db1d8-c02c-4678-ac0b-e48313e74e3c)

And the font-size in conf.py was deprecated, should become terminalFontSize

**Comment by spoorcc** [comment]
Maybe add something like https://github.com/wjdp/htmltest to prevent regressions in the future

**Comment by ben-edna** [comment]
Fixed in main
