### ISSUE TITLE
Svn & git mandated

### ISSUE THREAD

**Issue by spoorcc** [dfetch-org/dfetch#73]
Dfetch assumes both git and svn are available on the system. 

For example, If svn is not available in the path,  `dfetch import` will fail. 

Reported by @jgeudens

**Comment by jgeudens** [comment]
I have just installed the latest master of dfetch (36a2e5bb2faa9c13d478529cd06fd67ba79a873f).

As requested, here is more information, but I'm not sure if it is helpful:

```
dfetch import
  Dfetch (0.0.5)
  svn not available on system, please install


dfetch -v import
  Dfetch (0.0.5)
  Running svn info
  svn not available on system, please install
```
The issue is resolved by installing the `subversion` package on ubuntu.

**Comment by spoorcc** [comment]
Thanks for the update!
