### ISSUE TITLE
Update command defaults to SVN and stops on error

### ISSUE THREAD

**Issue by jgeudens** [dfetch-org/dfetch#74]
I found an open source project (https://github.com/ChristopherWilks/megadepth) on Github with some git submodules to test dfetch.

It appears that the current master of dfetch (36a2e5bb2faa9c13d478529cd06fd67ba79a873f) prefers SVN and stops with an error when the SVN handling fails. The import command works after installing the subversion package. But the following update fails with following message

```
dfetch -v update
  Dfetch (0.0.5)
  Looking for manifest
  Using manifest /home/jens/Projects/megadepth/dfetch.yaml
  Running svn info https://github.com/samtools/htslib
  Return code: 0
  stdout:
  Path: htslib
  URL: https://github.com/samtools/htslib
  Relative URL: ^/
  Repository Root: https://github.com/samtools/htslib
  Repository UUID: 179373a4-1820-8b07-f7c7-ce57b7db7bff
  Revision: 5945
  Node Kind: directory
  Last Changed Author: valeriu.ohan
  Last Changed Rev: 5945
  Last Changed Date: 2020-09-22 14:15:49 +0200 (di, 22 sep 2020)
  
  stderr:
  
    - htslib              : fetching (master - a7a90fe9)
  fetching htslib a7a90fe913f8a466f32f6e284cf46653944acd6f from https://github.com/samtools/htslib
  Running svn export --force  https://github.com/samtools/htslib/branches/master htslib_ci
  svn export --force  https://github.com/samtools/htslib/branches/master htslib_ci returned 1:
  svn: E205000: Try 'svn help export' for more information
  svn: E205000: Error parsing arguments
```

**Comment by spoorcc** [comment]
Github has a feature that it provides both an svn and git interface on the same url. Since svn works on this repo url, dfetch continues with that. But the svn interface expects trunk instead of master. 
I need to think about this a little. 

- force to git when branch is called master
- first check if branch is available and fall back to different repo type
- ....

**Comment by jgeudens** [comment]
During initial import, dfetch should be able to detect the type of VCS: externals (SVN) versus submodules (Git).

Maybe it is a good idea to add this info to the manifest and specify the VCS type per remote.

**Comment by spoorcc** [comment]
Problem here is that submodules with ssh checkouts are detected correctly, by http checkouts not.

Optionally an additional field `vcs: git` could solve it. But preferably dfetch would auto-detect. It could be somebody doesn't use import to start using dfetch. They then have to input another field when creating their manifest.

I think an educated guess can be done:
- see if git is in the url of the remote. e.g. Github/gitlab/git.mycompany.com.
- see if `repo-path` ends with `.git` (ssh case)
- see if remote contains branch/revision requested

And additionally a fallback that if svn fails, try it with git (and vice versa). In case all fails give a feedback of attempts that were taken:

Dfetch failed to update:
- <url> is valid svn url, but has no branch '<branch>'
- <url> is not a git repository

**Comment by ben-edna** [comment]
Something along the lines of this: https://stackoverflow.com/questions/38449143/how-to-detect-whether-a-given-remote-repository-is-a-git-repo-or-svn-repo

**Comment by ben-edna** [comment]
Ok, now the trick I used to test the svn interface using github broke. Sleeping another night on it 😄

**Comment by ben-edna** [comment]
I give up, I see no other way than to give the user the ability to explicitly state the vcs type. I want to stress the normal usecase should be that it is not needed.
