### ISSUE TITLE
Git short revisions ignored

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#80]
Currently short revisions are ignored for git. 

For now dfetch tries to fetch as efficiently as possible and it fetches only a specific sha/branch/tag. And in case of 'src' entry only the directory or file mentioned. 

With git as of now it seems that it is only possible to fetch a sha if it is the complete 40-char version. Short revisions are not accepted. 

One option would be to do an entire clone, checkout the short sha and warn the user that he should update his manifest with the long version. 

Another option would be to find some magic git command that can transform a short sha to a long one on the **remote** repo. So something like 
```
git rev-parse <short-sha>
```

**Comment by spoorcc** [comment]
Maybe https://stackoverflow.com/a/26694941/1149326?

**Comment by ben-edna** [comment]
`git rev-list` only works on local repo as far as I can see. 

An option could be to do a partial clone somewhere, find out the long sha, warn the user he should use the long sha because this is slow.

**Comment by ben-edna** [comment]
After consideration converting this into a feature and a design choice.
Changing this introduces several challenges and not much added value.
