### ISSUE TITLE
Update command fails with specific revisions in manifest

### ISSUE THREAD

**Issue by jgeudens** [dfetch-org/dfetch#81]
When a specific revision is mentioned in the manifest, dfetch can't find the specific revision.

Tested with current master (31d250ab533be0b9e650ba2a9c2873a52ff40c48)

```
Running git ls-remote https://github.com/google/googletest.git
Return code: 0
stdout:
...

stderr:

Running ['git', 'branch', '--contains', 'dcc92d0ab6c4ce022162a23566d44f673251eee4']
git branch --contains dcc92d0ab6c4ce022162a23566d44f673251eee4 returned 129:
error: no such commit dcc92d0ab6c4ce022162a23566d44f673251eee4
```

I have checked out the google test repo and ran the `git branch --contains dcc92d0ab6c4ce022162a23566d44f673251eee4` command and it returned `master` correctly.

If required, you can use following branch to reproduce the issue: https://github.com/jgeudens/ModbusScope/tree/dfetch_try2

**Comment by spoorcc** [comment]
Mmm, interesting

**Comment by ben-edna** [comment]
Ok, problem is that dfetch tries to find a branch containing a sha while there is no local repo. This is impossible.
I'm currently improving the git behavior in the sparse checkout branch. If it reaches master, I'll let you know
