### ISSUE TITLE
check command returns short revision of latest commit

### ISSUE THREAD

**Issue by jgeudens** [dfetch-org/dfetch#83]
The check command shows the current and latest revision of the repo, but it only shows the short revision. As I understand, it is better to use the full revision, so at the moment I still need to manually check the latest (full) revision of a repo to put in my manifest.

It would be easier that the check command shows the full revision so it can be copied easily to the manifest.

**Comment by spoorcc** [comment]
Good point!

**Comment by spoorcc** [comment]
I hope to fix #80 in the short term as well. But it is a challenge.
