### ISSUE TITLE
'/' appended to ssh url

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#94]
When using an git ssh url `git@github.com:cpputest/cpputest.git`, dfetch adds an extra '/' resulting in `git@github.com:cpputest/cpputest.git/` which is not a legal url

**Comment by ben-edna** [comment]
issue is in `ProjectEntry::remote_url`, too much joins and splits

**Comment by ben-edna** [comment]
Probably good to create a separate util function for safe joining, which skips:
- Empty strings `''`
- None types `None`
- Whitespace only `' '`

```
>>> a = ['', 'a', None, ' ', 'b', '']
>>> "/".join(filter(lambda x:  str(x or '').strip(), a))
'a/b'
```

**Comment by Rohitth007** [comment]
Hi, new to opensource, wanted to contribute. 
Why `split` at `"/"` when joining them back again? 
Can't we just `join` both paths and `strip` the result for corner case?

**Comment by spoorcc** [comment]
Welcome! Thanks for the suggestion. You're probably right, if you would like to contribute, a PR is always welcome. Otherwise I could also pick this up in a branch.
If you need any help, please let me know.

**Comment by Rohitth007** [comment]
I've sent a PR, but not sure what the Codacy error means.
Thx

**Comment by ben-edna** [comment]
Thanks for your help!
