### ISSUE TITLE
Add freeze command

### ISSUE THREAD

**Issue by ben-edna** [dfetch-org/dfetch#95]
Similar to pip freeze, create a command that takes all current  (on disk) versions and adds revisions/branches or tags for each project.

**Comment by jgeudens** [comment]
What kind of output would you expect from this command? Git and SVN?

Something like: 

    Scenario: Git projects are specified in the manifest
        Given the manifest 'dfetch.yaml'
            """
            manifest:
              version: '0.0'

              remotes:
                - name: github-com-dfetch-org
                  url-base: https://github.com/dfetch-org/test-repo

              projects:
                - name: ext/test-repo-rev-only
                  revision: e1fda19a57b873eb8e6ae37780594cbb77b70f1a
                  dst: ext/test-repo-rev-only

                - name: ext/test-rev-and-branch
                  revision: 8df389d0524863b85f484f15a91c5f2c40aefda1
                  branch: main
                  dst: ext/test-rev-and-branch

            """
        When I run "dfetch freeze"
        Then the output shows
            """
            Dfetch (0.1.0)
              ext/test-repo-rev-only==master@e1fda19a57b873eb8e6ae37780594cbb77b70f1a
              ext/test-rev-and-branch==main@8df389d0524863b85f484f15a91c5f2c40aefda1
            """

**Comment by ben-edna** [comment]
The goal is to: if a user didn't use a revision or branch in his manifest, he can add these automatically with `dfetch freeze`. The output should be somewhat similar to the check command and strive to keep it the same for git and svn. If I remember correctly the Version class has a `__repr__` method. You can then print the version using that. "Freezing version {version}".

 Implementation wise, all data should be in the dfetch_data.yaml metadata file. If it's a tag, only mention the tag, if it is a branch, use branch and commit. This should already work as mentioned above through the Version class. The hard part is changing the manifest.

Sidenote: Also consider the case that the current directory contents has a different hash than in the dfetch_data.yaml metadata file. (But this probably should be a different issue/feature).

**Comment by ben-edna** [comment]
I've created a branch `feature/freeze-command` for this.
